# vi: ft=toml

[".asdf"]
  type = "git-repo"
  url = "https://github.com/asdf-vm/asdf.git"
  clone.args = ["--depth", "1"]
  refreshPeriod = "168h"

[".config/k9s/skin.yml"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/k9s/main/dist/mocha.yml"
  refreshPeriod = "168h"

[".vim/pack/hugginsio/start/eunuch"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-eunuch.git"
  clone.args = ["--depth", "1"]
  refreshPeriod = "168h"
