" Acknowledgements:
" https://github.com/amix/vimrc
" https://github.com/michaeljmcd/dotfiles

" Leader
let mapleader=" "
let maplocalleader=" "
nnoremap <SPACE> <Nop>

" Set relative and normal  numbers.
set nu rnu

" Theme
set termguicolors

" Ignore common files and directories.
set wildignore=*.o,*~,*.pyc,*.dll,*.pdb,*.nupkg,*.exe,*.jpg,*.png,*.bin,tags,**/target/**,**/node_modules/**
if has("win16") || has("win32")
    set wildignore+=.git\*,.hg\*,.svn\*
else
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
endif

" Visual mode pressing * or # searches for the current selection (from Michael Naumann).
vnoremap <silent> # :<C-u>call VisualSelection('', '')<CR>?<C-R>=@/<CR><CR>

" Remap VIM 0 to first non-blank character.
map 0 ^

" Delete trailing white space on save, useful for some filetypes.
fun! CleanExtraSpaces()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    silent! %s/\s\+$//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfun

if has("autocmd")
    autocmd BufWritePre *.txt,*.md,*.csv :call CleanExtraSpaces()
endif

" Disable scrollbars.
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L

" Enable persistent undo.
try
    if !isdirectory($HOME . "/.vim/undo")
        call mkdir($HOME . "/.vim/undo", "p", 0700)
    endif

    set undodir=~/.vim/undo
    set undofile
catch
endtry

" Bash like keys for the command line.
cnoremap <C-A>		<Home>
cnoremap <C-E>		<End>
cnoremap <C-K>		<C-U>
cnoremap <C-P> <Up>
cnoremap <C-N> <Down>

" Shortcut for timestamp.
iab xdate <C-r>=strftime("%Y-%m-%d %H:%M:%S")<cr>

" YAML particulars.
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" Backup to ~/.vim/backup.
if !isdirectory($HOME . "/.vim/backup")
    call mkdir($HOME . "/.vim/backup", "p", 0700)
endif

set backup
set backupdir=~/.vim/backup
set backupskip=~/.vim/backup
set directory=~/.vim/backup
set writebackup

" Open Netrw
if !has("nvim")
    hi! link netrwMarkFile Search
    let g:netrw_banner=0
    let g:netrw_browse_split = 4
    let g:netrw_fastbrowse=0
    let g:netrw_hide=1
    let g:netrw_keepdir=0
    let g:netrw_list_hide='^\./$'
    let g:netrw_liststyle=0
    let g:netrw_localcopydircmd='cp -r'
    let g:netrw_winsize=20
    nnoremap <silent> <leader>e :Lexplore<CR>
endif

au FileType netrw setl bufhidden=wipe
au FocusGained,BufEnter * checktime
set ai
set belloff=all
set cmdheight=1
set commentstring=""
set complete=.,w,b,u,t,kspell
set encoding=utf-8
set expandtab
set ffs=unix,dos,mac
set fillchars=""
set hidden
set hlsearch
set ignorecase
set magic
set modelines=3
set mouse=vcr
set mousemodel=popup_setpos
set noerrorbells
set nofsync
set noshowmode
set nostartofline
set novisualbell
set regexpengine=0
set shortmess=aoOtTF
set showcmd
set showmatch
set si
set signcolumn=yes
set smartcase
set splitbelow
set splitright
set switchbuf=uselast
set t_vb=
set ttyfast
set whichwrap+=<,>,h,l
set wildoptions="pum,tagfile"
set wrap
