#!/usr/bin/env sh

# global settings
yabai -m config                                 \
    mouse_follows_focus          on             \
    focus_follows_mouse          on             \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  0              \
    bottom_padding               0              \
    left_padding                 0              \
    right_padding                0              \
    window_gap                   0              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

echo "yabai configuration loaded."
