gui:
    mouseEvents: false
    showBottomLine: false
    showCommandLog: true
    showFileTree: false
    showIcons: false
    showRandomTip: false
    theme:
        selectedLineBgColor:
            - reverse
            - black
            - bold
        selectedRangeBgColor:
            - blue
