gui:
    mouseEvents: false
    showBottomLine: false
    showCommandLog: false
    showFileTree: false
    showIcons: false
    showRandomTip: false
    theme:
        selectedLineBgColor:
            - black
            - bold
        selectedRangeBgColor:
            - blue
