# https://starship.rs
"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nix_shell\
$direnv\
$line_break\
$status\
$os\
$container\
$character
"""
right_format = """
$cmd_duration
"""

[directory]
repo_root_style = "bold cyan"
style = "cyan"
truncation_length = 4
truncation_symbol = "…/"

[cmd_duration]
format = "[$duration]($style)"
min_time = 5_000
show_milliseconds = true
style = "dimmed text"
