# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  clean:
    cmd: docker images -a | grep none | awk '{ print $3; }' | xargs docker rmi --force
    desc: Remove dangling, nameless images.
  build:ubuntu:
    cmd: docker build --file=Dockerfile.ubuntu --tag=dev:ubuntu .
    desc: Build the Ubuntu image.
  run:ubuntu:
    cmd: docker run -it dev:ubuntu
    desc: Launch an interactive shell in the Ubuntu image.
