[notebook]
dir = "~/Workspaces/zk"

[note]
default-title = "Untitled"
extension = "md"
filename = "{{id}}-{{slug title}}"
language = "en"

# Relative to .zk/templates/
template = "default.md"

# Configure random ID generation.
id-case = "lower"
id-charset = "alphanum"
id-length = 4

[group.journal.note]
filename = "{{format-date now}}"

[format.markdown]
colon-tags = true
hashtags = false
multiword-tags = false

[tool]
editor = "nvim"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"

[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
