[notebook]
dir = "~/Workspaces/zk/"

[note]
default-title = "Untitled"
extension = "md"
filename = "{{id}}-{{slug title}}"
language = "en"

# Relative to zk/templates/
template = "default.md"

# Configure random ID generation.
id-case = "lower"
id-charset = "alphanum"
id-length = 4

[group.journal]
paths = ["journal"]

[group.journal.note]
template = "journal.md"

[group.work-item]
paths = ["work-item"]

[group.work-item.note]
template = "work-item.md"

[format.markdown]
colon-tags = false
hashtags = false
multiword-tags = false

[tool]
editor = "nvim"
fzf-line = "{{#if metadata.work-item}}{{#style 'path'}}{{metadata.work-item}}{{/style}} {{/if}}{{style 'title' title}}"
fzf-preview = "bat -l md -p --color always {-1}"
pager = "less -FIRX"

[filter]
journal = "--sort created journal"
recent = "--sort created- --created-after 'last two weeks'"

[alias]
alias = 'yq ".alias" ~/.config/zk/config.toml -oy'
ed = 'zk edit --sort modified- --interactive "$@"'
edclosed = 'zk ed -t "work-item, closed"'
edlast = 'zk edit --limit 1 --sort modified- "$@"'
edpending = 'zk ed -t "work-item, NOT closed"'
ewi = 'zk ed -t "work-item"'
ls = 'zk list --sort modified- -foneline "$@"'
lsclosed = 'zk lwi -t "closed"'
lspending = 'zk lwi -t "NOT closed"'
lucky = 'zk list --quiet --format full --sort random --limit 1'
lwi = 'zk ls -f "{{#style \"path\"}}{{metadata.work-item}}{{/style}} {{style \"title\" metadata.title}} {{#if metadata.install-date}}({{metadata.install-date}}){{/if}}" -t "work-item" "$@"'
recent = 'zk edit --sort created- --created-after "last two weeks" --interactive'
today = 'zk-journal "$ZK_NOTEBOOK_DIR" today'
tomorrow = 'zk-journal "$ZK_NOTEBOOK_DIR" tomorrow'
uwi = 'zk-update-work-item $ZK_NOTEBOOK_DIR'
vwi = 'zk-view-work-item $OLDPWD $ZK_NOTEBOOK_DIR $1'
yesterday = 'zk-journal "$ZK_NOTEBOOK_DIR" yesterday'

[lsp]
[lsp.diagnostics]
dead-link = "error"
wiki-title = "none"
