[notebook]
dir = "~/Workspaces/zk/"

[note]
default-title = "Untitled"
extension = "md"
filename = "{{id}}-{{slug title}}"
language = "en"

# Relative to zk/templates/
template = "default.md"

# Configure random ID generation.
id-case = "lower"
id-charset = "alphanum"
id-length = 4

[group.journal]
paths = ["journal"]

[group.journal.note]
filename = "{{format-date now}}"
template = "journal.md"

[format.markdown]
colon-tags = false
hashtags = false
multiword-tags = false

[tool]
editor = "nvim"
fzf-preview = "bat -p --color always {-1}"
pager = "less -FIRX"

[filter]
journal = "--sort created journal"
recents = "--sort created- --created-after 'last two weeks'"

[alias]
ed = "zk edit --interactive $@"
edlast = "zk edit --limit 1 --sort modified- $@"
journal = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'
ls = "zk list -foneline $@"
lucky = "zk list --quiet --format full --sort random --limit 1"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

[lsp]
[lsp.diagnostics]
dead-link = "error"
wiki-title = "none"
