[notebook]
dir = "~/Workspaces/zk/"

[note]
default-title = "Untitled"
extension = "md"
filename = "{{id}}-{{slug title}}"
language = "en"

# Relative to zk/templates/
template = "default.md"

# Configure random ID generation.
id-case = "lower"
id-charset = "alphanum"
id-length = 4

[group.journal]
paths = ["journal"]

[group.journal.note]
filename = "{{format-date now}}"
template = "journal.md"

[group.work-item]
paths = ["work-item"]

[group.work-item.note]
template = "work-item.md"

[format.markdown]
colon-tags = false
hashtags = false
multiword-tags = false

[tool]
editor = "nvim"
fzf-preview = "bat -p --color always {-1}"
pager = "less -FIRX"

[filter]
journal = "--sort created journal"
recent = "--sort created- --created-after 'last two weeks'"

[alias]
alias = 'yq ".alias" ~/.config/zk/config.toml -oy'
ed = 'zk edit --sort modified- --interactive "$@"'
edclosed = 'zk ed -t "work-item, closed"'
edlast = 'zk edit --limit 1 --sort modified- "$@"'
edpending = 'zk ed -t "work-item, NOT closed"'
journal = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'
ls = 'zk list -foneline "$@"'
lsclosed = 'zk ls -t "work-item, closed"'
lspending = 'zk ls -t "work-item, NOT closed"'
lucky = 'zk list --quiet --format full --sort random --limit 1'
nwi = 'zk-new-work-item $1 $ZK_NOTEBOOK_DIR'
recent = 'zk edit --sort created- --created-after "last two weeks" --interactive'
vwi = 'zk edit $(rg -l "work-item: $1" $ZK_NOTEBOOK_DIR)'
wi = 'zk edit -i -t "work-item"'

[lsp]
[lsp.diagnostics]
dead-link = "error"
wiki-title = "none"
